### ISSUE TITLE
shotcut key conflict

### ISSUE THREAD

**Issue by mortee** [k5md/Pocket-Editor-webextension#6]
Both Pocket Editor and another sidebar extension I use have Ctrl-Shift-Y as their shortcut key. And that always brings up the other extension while I'd like to access PE. Any way to fix this?

**Comment by k5md** [comment]
Hi, @mortee , all shortcuts for web-extensions are recommendations, so that they are supposed to be remapped by default. I guess, FF team did a great job at hiding settings for configuring extensions' shortcuts: you have to go open Application Menu -> Add-ons and Themes -> Extensions -> Pocket Editor -> Tools for all add-ons (top-right cog icon) ->Manage Extension Shortcuts. In this menu you can remap default PE shortcut.
![pe_shortcuts](https://user-images.githubusercontent.com/6698666/144968883-199cedbe-fd0e-409a-abfc-6ac2623df488.png)

**Comment by mortee** [comment]
thanks, yes, that obviously solves it. funny thing I've been a continuous mozilla/firefox user for at least 19 years, and I didn't know this thing existed (:
