### ISSUE TITLE
Auto-focus new editor

### ISSUE THREAD

**Issue by mortee** [k5md/Pocket-Editor-webextension#8]
When I open a new editor, naturally I do it so that I can quickly type or paste something to it. The fact that it doesn't get automatically focused, and even not the entire editor accepts click to focus, just the first line, is really inconvenient. It should be focused automatically.

**Comment by k5md** [comment]
Hello again, @mortee ! I've just thought that potential users would find the current behaviour non-intuitive (having to hit not even somewhere, but exactly on the first line of new document to input text) and think that the addon is not working. I did some research on whether this feature you requested could be implemented with native sidebar, at least partially (autofocus on extension open / keyboard shortcut pressed), and it turns out to be [another one of these 4+ years old firefox bugs](https://bugzilla.mozilla.org/show_bug.cgi?id=1502713).
I introduced a (not really clean for now) workaround for autofocusing on switching active document, as well as another one, allowing to start inputting text after clicking on any document place. Autofocus on extension's sidebar, though, is not possible (hopefully, only for now) when using native ff sidebar API. The only way seems to fake a sidebar inside currently active tab via injecting code in it and spawning a frame for sidebar content, however, this approach is overly unsafe and complicated.

**Comment by mortee** [comment]
Hey @k5md, sure, this fake sidebar injected into the active page would be a bad idea on many levels. If proper autofocus is not possible, then a workaround as good as it gets will do, sure. Anyway, is it impossible even if the sidebar itself already has focus (e.g. by having the user clicked on a button in it, like "new"), just it needs to be directed to the text input field?

**Comment by k5md** [comment]
If sidebar is already focused, everything works fine, it's a regular page, just in a separate window frame after all.
I implemented this functionality and published new version ~2 days ago. It must work now. If you have disabled automatic addon updates, check Pocket Editor version installed (latest is 0.5.0) and update through Application Menu -> Add-ons and Themes -> Extensions -> Pocket Editor -> Tools for all add-ons (top-right cog icon) ->Check for updates and restart FF. If it doesn't autofocus on new/imported/switched documents, I'll have a closer look at this.

**Comment by mortee** [comment]
Works like a charm, awesome!
