### ISSUE TITLE
all my documennts are gone

### ISSUE THREAD

**Issue by mortee** [k5md/Pocket-Editor-webextension#9]
Using Pocket Editor 0.5.0 on win 10 Firefox 103. After a system restart, when I opened PE again, all my docs are gone, and the welcome doc is the only one I can see. What might have happened, and how do I recover my docs??

**Comment by k5md** [comment]
Hello, @mortee . I've checked that updating FF to 103.0 does not cause documents created in PE disappear. It certainly happens when you delete the extension or clear offline web site data (since docs are stored in the extension's indexedDB), as well as when you're switching firefox profiles, or may possibly (I haven't tested this) happen when you are logging into/out from your FF account under the same firefox profile. I want to help, but none of this actions can be caused or reverted by PE.
We can quickly try to see what the storage looks like:

1. Go to [about:debugging#/runtime/this-firefox](about:debugging#/runtime/this-firefox)
2. In "Extensions" section find Pocket Editor, click on "Inspect"
3. In the opened tab paste the following in the console then press 'Enter':
```
parseDeep = (obj) => Object.entries(obj).reduce((acc, [key, val]) => {
  try {
    return {...acc, [key]: parseDeep(JSON.parse(val))};
  } catch (e) {
    return {...acc, [key]: val};
  }
}, {});
indexedDB.open("pocketEditor", 1).onsuccess = (event) => {
  let db = event.target.result;
  let tx = db.transaction("keyval", "readonly");
  let store = tx.objectStore('keyval');
  let request = store.getAll();
  tx.oncomplete = () => {
    let storage = parseDeep({'store': request.result});
    let documents = storage.store.editorReducer.documents;
    console.dir(documents);
  };
};
```
This will give you a list of all documents in PE storage in your firefox profile. Should you find missing documents in this list, they can be recovered, otherwise they are either deleted or in other profile.

**Comment by mortee** [comment]
Hi, thanks for the quick reply, I've been on the road, hence the delay. So, the above code throws `db is undefined` at line 8, `let tx = db.tr...`

**Comment by k5md** [comment]
Sorry, I guess I've messed it up when copypasting from console, I've updated the code

**Comment by mortee** [comment]
It's definitely only the greetings doc 😔
